-- Matches function/sheet_sync/rules/EW_COMPLETE_RULES.yaml → postgres.table / columns

CREATE TABLE IF NOT EXISTS ltl_pod_complete (
    ew_quote_no TEXT PRIMARY KEY,
    col_a_seq TEXT,
    dhg_pod_date TEXT,
    quote_company TEXT,
    mark_box TEXT,
    pod_delivered_billed TEXT,
    ctn_total TEXT,
    goods_description TEXT,
    ship_from TEXT,
    consignee_contact TEXT,
    consignee_address TEXT,
    weight_lbs TEXT,
    dimensions_class TEXT,
    volume_m3 TEXT,
    cargo_value TEXT,
    ew_quote_link TEXT,
    miles TEXT,
    consignee_residential TEXT,
    col_s_empty TEXT,
    total_dat TEXT,
    drive TEXT,
    ratio_26_13 TEXT,
    coefficient TEXT,
    dat_per_pallets TEXT,
    pr1 TEXT,
    x4pll_quote TEXT,
    pr1_dat_half TEXT,
    dat_sales_price TEXT,
    dat_sales_price_11 TEXT,
    dat_sales_price_12 TEXT,
    dat_sales_price_13 TEXT,
    row_seq TEXT,
    synced_at TIMESTAMPTZ DEFAULT NOW()
);
